### PR TITLE
Update versions and docs

### PR DESCRIPTION
**Pull request by windymilla**
This is not for merging quite (since version of ebookmaker is a beta), but would love to have a review, please.
Will push another commit when non-beta ebookmaker is released

1. Python 3.10 is available
2. Visual Studio download is now on 2022 version
3. New ebookmaker (currently a beta)
4. New ebookmaker no longer uses tidy

### CODE REVIEW

**Comment by cpeel** [comment]
These look great so far. Will keep an eye out for the follow-up commit with the non-beta EBM.

**Comment by windymilla** [comment]
@cpeel, I have hopefully now done what is necessary to update to the non-beta version of Ebookmaker that Eric has released. If you think this is all OK, I'm ready to merge - thanks.

**Review by cpeel — APPROVED** [review]
This all looks great to me. Great job on updating this -- I know it's a bit of a squirrely process.

**Comment by windymilla** [comment]
> This all looks great to me. Great job on updating this -- I know it's a bit of a squirrely process.

Thanks. I had a great teacher

**Review by srjfoo — APPROVED** [review]

**Pull request merged**
